### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by starkoracles** [MarcoCiaramella/sha256-gpu#2]
@MarcoCiaramella thanks for implementing it, this is great! I've been thinking about using it for a project I'm working on, but I wasn't able to get very good performance numbers. I'm getting about a 4s running time to run 131k messages, each message is of size 576 bytes. 

I'm not very familiar in working with webgpu, so I'm not sure if I'm doing wrong or this is the expected performance, do you have any thoughts?

**Comment by MarcoCiaramella** [comment]
@starkoracles thanks for using this module! Can you provide me more info about your system? Are you using Chrome? I haven't do a performace test but 4s for 131k messages is a poor performance, worse than CPU version.

**Comment by starkoracles** [comment]
Yep, first thanks for answering so quickly!

I'm using chrome (new version) on a Mac M1 system.

I've tried to run the chrome built in profiler and it wasn't able to tell me much about what happens behind the scenes, do you have recommendations for other tools that can be used for that? 

As a code reference: https://github.com/starkoracles/Aero/blob/webgpu-experiment/aero-sdk/src/sdk.ts#L33, this is how I'm using the module. What it essentially does is write a bunch of byte arrays to a dom element from wasm (Rust) and then I read them and call your module, so it's fairly similar to the example in the readme.

I'd love for any suggestions or thoughts you might have. I'm also happy to dump the messages array into a file and upload it to this repo so we can get a minimal example and compare result, how does that sound?

**Comment by MarcoCiaramella** [comment]
@starkoracles thank you for reporting this issue! I have done an optimization over the js part where there was an expensive buffer handling. Now it performs 10x with 131k messages of 576bytes compared to the CPU version. Anyway keep in mind that there is always an overhead when you try to run shader on GPU due to data binding and initialization phase. So under certain circumstances running on GPU may result in a worse perfomance compared to the CPU version for example when you have to process few small messages.


About the new module version see the new example in the readme. I changed the function interface.

**Comment by MarcoCiaramella** [comment]
@starkoracles let me know how it works now. Thanks!

**Comment by starkoracles** [comment]
@MarcoCiaramella thanks for such a quick reply, amazing work!

I was able to test it and it worked great! Your fix got it down to 336ms on my computer which is an amazing result! I currently use blake2s hash function, so I will have to add a shader implementation for it, but it's super helpful to have your library as an example, I would love to work on it together. 

My next step will probably be to switch to have the wrapper code around the shader to the rs library so I can call it directly from my Rust code, I'm curious how it performs compared to the js implementation, I will update you! 

One comment, for some reason, after I upgraded to 1.1 the DOMContentLoaded event was never called anymore, I wonder if something in your library blocks it from being called? I'm not super familiar with js internals, so I just replaced it with setTimeout in my init code which worked around it.

**Comment by MarcoCiaramella** [comment]
@starkoracles 

> I was able to test it and it worked great! Your fix got it down to 336ms on my computer which is an amazing result! I currently use blake2s hash function, so I will have to add a shader implementation for it, but it's super helpful to have your library as an example, I would love to work on it together.

Cool! yes you can use as a starting point for blake2s. Write me back if you need support or anything else!

> My next step will probably be to switch to have the wrapper code around the shader to the rs library so I can call it directly from my Rust code, I'm curious how it performs compared to the js implementation, I will update you!

Nice one, let me know how it works!

> One comment, for some reason, after I upgraded to 1.1 the DOMContentLoaded event was never called anymore, I wonder if something in your library blocks it from being called? I'm not super familiar with js internals, so I just replaced it with setTimeout in my init code which worked around it.

ok I removed await statement from top level. Try now with 1.1.1 version. Thanks!
