### ISSUE TITLE
Does it support long content input?

### ISSUE THREAD

**Issue by winktool** [MarcoCiaramella/sha256-gpu#4]

**Comment by MarcoCiaramella** [comment]
hello @winktool ! what do you mean for long input?
The function takes an array of N messages of M bytes and processes them in parallel. For example you can pass an array of 4 messages of 1 byte each. Or an array of 1000 messages of 1MB each.

**Comment by winktool** [comment]
I tried it and if the data I enter is a long piece of hex, then I get the wrong result.
Also, is there a version for single data?

**Comment by MarcoCiaramella** [comment]
@winktool can you paste the code here? thanks

> Also, is there a version for single data?

you can pass one message but in this case the performance could be worse than the CPU version due to the GPU binding memory overhead

**Comment by winktool** [comment]
```
0100000001ffe8208acf0f69b5333ff5701a41c83ca688c16536b48a488921a20b3b1761932400000000ffffffff02c01f0200000000002251208db78f8cb3622355cae7d5021d1b9cb38d9afd2a96d6b6386970b7a4638e133300000000000000000a6a082f40d38515337cc900000000
```
plz input this hex

**Comment by winktool** [comment]
Please teach me how to deal with this situation

**Comment by MarcoCiaramella** [comment]
that is a bitcoin block header in hexadecimal format. You cannot input hexadecimal string.  The `sha256_gpu` function takes array of bytes so you have to convert the block header to an array of bytes. You can find examples online, I cannot support you in this.

**Comment by winktool** [comment]
Thanks
